[package]
name = "runtime"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.42"
wasmer = "2.0.0"
serde = { version = "1.0" }
serde_cbor = { package = "cs_serde_cbor", version = "0.12" }
shared = { path = "../shared" }